run:
  timeout: 5m
  skip-dirs:
    - bench

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive
    - misspell
    - errcheck

issues:
  exclude-use-default: false
