max_concurrency = 4
timeout = 20
exclude_private = true
accept = ["200..299", "403"]

# Temporarily exclude pkg.go.dev until Go Docs recognizes the new module (24-48 hours after first push)
exclude = ["https://pkg.go.dev/github.com/YuminosukeSato/pyproc"]
