package tests

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestE2E_SchemaExportToTypedAPI(t *testing.T) {
	// 1. Create Python worker with type hints
	workerScript, err := filepath.Abs("fixtures/typed_worker.py")
	require.NoError(t, err)

	// 2. Export schema using pyproc-worker CLI
	cmd := exec.Command("pyproc-worker", "schema", workerScript, "--format", "go")
	schemaOutput, err := cmd.Output()
	if err != nil {
		// pyproc-worker might not be installed - skip test
		t.Skipf("pyproc-worker not available, skipping: %v", err)
	}

	// 3. Parse generated structs (validate structure)
	goCode := string(schemaOutput)
	assert.Contains(t, goCode, "package main")
	assert.Contains(t, goCode, "// Generated by pyproc-worker schema --format go")

	// Check that request/response structs are generated
	assert.Contains(t, goCode, "type PredictRequest struct")
	assert.Contains(t, goCode, "type PredictResponse struct")
	assert.Contains(t, goCode, "type TransformRequest struct")
	assert.Contains(t, goCode, "type TransformResponse struct")
	assert.Contains(t, goCode, "type PreprocessRequest struct")
	assert.Contains(t, goCode, "type PreprocessResponse struct")

	// 4. Write to temp Go file
	tempDir := t.TempDir()
	tempGoFile := filepath.Join(tempDir, "generated_types.go")
	err = os.WriteFile(tempGoFile, schemaOutput, 0644)
	require.NoError(t, err)

	// 5. Verify Go syntax by running gofmt
	cmd = exec.Command("gofmt", "-l", tempGoFile)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Logf("gofmt output: %s", output)
		t.Logf("Generated code:\n%s", goCode)
	}
	require.NoError(t, err, "Generated Go code should be valid Go syntax")

	t.Logf("✅ Schema export generated valid Go code with %d lines", strings.Count(goCode, "\n"))
}

func TestE2E_SchemaExportJSON(t *testing.T) {
	// Test JSON format schema export
	workerScript, err := filepath.Abs("fixtures/typed_worker.py")
	require.NoError(t, err)

	cmd := exec.Command("pyproc-worker", "schema", workerScript, "--format", "json")
	schemaOutput, err := cmd.Output()
	if err != nil {
		t.Skipf("pyproc-worker not available, skipping: %v", err)
	}

	// Validate JSON structure
	jsonSchema := string(schemaOutput)
	assert.Contains(t, jsonSchema, "\"functions\"")
	assert.Contains(t, jsonSchema, "\"predict\"")
	assert.Contains(t, jsonSchema, "\"transform\"")
	assert.Contains(t, jsonSchema, "\"preprocess\"")

	t.Logf("✅ Schema export generated valid JSON with %d bytes", len(schemaOutput))
}

func TestE2E_SchemaExportSimpleWorker(t *testing.T) {
	// Test schema export with simple worker (no complex types)
	workerScript, err := filepath.Abs("fixtures/simple_worker.py")
	require.NoError(t, err)

	cmd := exec.Command("pyproc-worker", "schema", workerScript, "--format", "go")
	schemaOutput, err := cmd.Output()
	if err != nil {
		t.Skipf("pyproc-worker not available, skipping: %v", err)
	}

	goCode := string(schemaOutput)
	assert.Contains(t, goCode, "package main")
	assert.Contains(t, goCode, "type EchoRequest struct")
	assert.Contains(t, goCode, "type AddRequest struct")
	assert.Contains(t, goCode, "type UppercaseRequest struct")

	t.Logf("✅ Simple worker schema export successful")
}

func TestE2E_SchemaExportComplexWorker(t *testing.T) {
	// Test schema export with complex types (nested, dataclasses)
	workerScript, err := filepath.Abs("fixtures/complex_worker.py")
	require.NoError(t, err)

	cmd := exec.Command("pyproc-worker", "schema", workerScript, "--format", "go")
	schemaOutput, err := cmd.Output()
	if err != nil {
		t.Skipf("pyproc-worker not available, skipping: %v", err)
	}

	goCode := string(schemaOutput)
	assert.Contains(t, goCode, "package main")
	assert.Contains(t, goCode, "type ProcessNestedRequest struct")
	assert.Contains(t, goCode, "type CalculateDistanceRequest struct")
	assert.Contains(t, goCode, "type AggregateDataRequest struct")

	t.Logf("✅ Complex worker schema export successful")
}
