apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - service-account.yaml
labels:
  - pairs:
      cloud: azure
    includeSelectors: false
patches:
  - path: sa-annotation-patch.yaml
  - path: pod-label-patch.yaml
