"""Command-line interface for pyproc-worker."""

from __future__ import annotations

import argparse
import importlib.util
import json
import logging
import sys
from pathlib import Path


def _load_worker_module(worker_script: str):
    """Load a worker module from a file path."""
    spec = importlib.util.spec_from_file_location("worker", worker_script)
    if spec and spec.loader:
        worker_module = importlib.util.module_from_spec(spec)
        sys.modules["worker"] = worker_module
        spec.loader.exec_module(worker_module)
        return worker_module
    msg = f"Failed to load worker module from {worker_script}"
    raise ImportError(msg)


def _handle_array_type(schema: dict) -> str:
    """Convert JSON schema array type to Go type."""
    items = schema.get("items", {})
    if isinstance(items, dict):
        return f"[]{_json_schema_to_go_type(items)}"
    return "[]interface{}"


def _handle_object_type(schema: dict) -> str:
    """Convert JSON schema object type to Go type."""
    if "additionalProperties" in schema:
        value_type = _json_schema_to_go_type(schema["additionalProperties"])
        return f"map[string]{value_type}"
    if "properties" in schema:
        return "struct"
    return "map[string]interface{}"


def _json_schema_to_go_type(schema: dict) -> str:
    """Convert JSON schema to Go type string."""
    schema_type = schema.get("type", "any")

    type_mapping = {
        "integer": "int",
        "number": "float64",
        "string": "string",
        "boolean": "bool",
        "null": "interface{}",
    }

    if schema_type in type_mapping:
        return type_mapping[schema_type]
    if schema_type == "array":
        return _handle_array_type(schema)
    if schema_type == "object":
        return _handle_object_type(schema)
    return "interface{}"


def _generate_go_struct(name: str, schema: dict, indent: int = 0) -> str:
    """Generate Go struct definition from schema."""
    if schema.get("type") != "object" or "properties" not in schema:
        return ""

    indent_str = "\t" * indent
    lines = [f"{indent_str}type {name} struct {{"]

    properties = schema["properties"]
    required = schema.get("required", [])

    for field_name, field_schema in properties.items():
        # Convert snake_case to PascalCase
        go_field_name = "".join(word.capitalize() for word in field_name.split("_"))

        field_type = _json_schema_to_go_type(field_schema)

        # If field is not required and not a pointer type, make it a pointer
        if field_name not in required and not field_type.startswith("*"):
            field_type = f"*{field_type}"

        json_tag = f'`json:"{field_name}"`'
        lines.append(f"{indent_str}\t{go_field_name} {field_type} {json_tag}")

    lines.append(f"{indent_str}}}")
    return "\n".join(lines)


def _generate_go_code(schemas: dict) -> str:
    """Generate Go code from function schemas."""
    lines = [
        "package main",
        "",
        "// Generated by pyproc-worker schema --format go",
        "// This is a skeleton - you may need to adjust types manually",
        "",
    ]

    functions = schemas.get("functions", {})

    # Collect unique struct types
    structs_generated = set()

    for func_name, func_schema in functions.items():
        # Generate request/response struct names
        request_name = f"{func_name.replace('_', ' ').title().replace(' ', '')}Request"
        response_name = f"{func_name.replace('_', ' ').title().replace(' ', '')}Response"

        # Generate request struct
        if func_schema.get("parameters"):
            param = func_schema["parameters"][0]
            param_schema = param.get("type", {})

            if (
                param_schema.get("type") == "object"
                and "properties" in param_schema
                and request_name not in structs_generated
            ):
                struct_code = _generate_go_struct(request_name, param_schema)
                if struct_code:
                    lines.append(struct_code)
                    lines.append("")
                    structs_generated.add(request_name)

        # Generate response struct
        return_schema = func_schema.get("return_type", {})
        if (
            return_schema.get("type") == "object"
            and "properties" in return_schema
            and response_name not in structs_generated
        ):
            struct_code = _generate_go_struct(response_name, return_schema)
            if struct_code:
                lines.append(struct_code)
                lines.append("")
                structs_generated.add(response_name)

    return "\n".join(lines)


def run_command(args):
    """Run the worker (default behavior)."""
    # Set up logging
    logging.basicConfig(
        level=getattr(logging, args.log_level.upper()),
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    # Load and run the worker script
    _load_worker_module(args.worker_script)


def _detect_virtual_env() -> tuple[str | None, str | None]:
    """Detect virtual environment type and path.

    Returns:
        Tuple of (env_type, env_path) where env_type is one of:
        - "venv" for standard venv
        - "virtualenv" for virtualenv
        - "poetry" for Poetry environments
        - "uv" for uv environments
        - None if not in a virtual environment

    """
    if sys.prefix == sys.base_prefix:
        return None, None

    venv_path = sys.prefix

    # Check for Poetry (pyproject.toml with [tool.poetry])
    current = Path.cwd()
    for parent in [current, *current.parents]:
        pyproject = parent / "pyproject.toml"
        if pyproject.exists():
            content = pyproject.read_text()
            if "[tool.poetry]" in content:
                return "poetry", venv_path

    # Check for uv (.venv directory + uv binary)
    if (Path.cwd() / ".venv").exists():
        return "uv", venv_path

    # Check for virtualenv (has virtualenv.py)
    if (Path(venv_path) / "lib" / "virtualenv.py").exists():
        return "virtualenv", venv_path

    # Default to venv
    return "venv", venv_path


def detect_env_command(args):
    """Detect Python environment and output configuration."""
    env_type, env_path = _detect_virtual_env()

    python_version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    detection_result = {
        "python_executable": sys.executable,
        "python_version": python_version,
        "virtual_env_type": env_type,
        "virtual_env_path": env_path,
    }

    if args.format == "json":
        output = json.dumps(detection_result, indent=2)
        print(output)
    elif args.format == "shell":
        print(f"export PYPROC_PYTHON_EXEC={detection_result['python_executable']}")
        if detection_result["virtual_env_path"]:
            print(f"export VIRTUAL_ENV={detection_result['virtual_env_path']}")


def schema_command(args):
    """Export function schemas."""
    # Suppress worker logging during schema export
    logging.basicConfig(level=logging.ERROR)

    # Load the worker module (this will trigger @expose decorators)
    _load_worker_module(args.worker_script)

    # Import pyproc_worker to access schemas
    import pyproc_worker

    schemas = pyproc_worker.get_exposed_schemas()

    # Generate output based on format
    if args.format == "json":
        output = json.dumps(schemas, indent=2)
    elif args.format == "go":
        output = _generate_go_code(schemas)
    else:
        output = json.dumps(schemas, indent=2)

    # Write to file or stdout
    if args.output:
        Path(args.output).write_text(output)
    else:
        print(output)


def main() -> None:
    """Run the main entry point for CLI."""
    parser = argparse.ArgumentParser(
        description="Python worker for pyproc - Call Python from Go without CGO",
    )

    # For backward compatibility, check if first argument is a subcommand
    if len(sys.argv) > 1 and sys.argv[1] in ["schema", "detect-env"]:
        # Use subcommand mode
        subparsers = parser.add_subparsers(dest="command", help="Available commands")

        # Schema command
        schema_parser = subparsers.add_parser("schema", help="Export function schemas")
        schema_parser.add_argument("worker_script", help="Path to the Python worker script")
        schema_parser.add_argument(
            "--format",
            choices=["json", "go"],
            default="json",
            help="Output format (json or go)",
        )
        schema_parser.add_argument(
            "--output",
            "-o",
            help="Output file path (default: stdout)",
        )

        # Detect-env command
        detect_env_parser = subparsers.add_parser(
            "detect-env",
            help="Auto-detect Python environment",
        )
        detect_env_parser.add_argument(
            "--format",
            choices=["json", "shell"],
            default="json",
            help="Output format (json or shell)",
        )

        args = parser.parse_args()

        if args.command == "schema":
            schema_command(args)
        elif args.command == "detect-env":
            detect_env_command(args)
    else:
        # Default mode: run worker (backward compatibility)
        parser.add_argument("worker_script", help="Path to the Python worker script")
        parser.add_argument(
            "--socket-path",
            help="Unix domain socket path (overrides PYPROC_SOCKET_PATH)",
            default=None,
        )
        parser.add_argument(
            "--log-level",
            help="Logging level",
            choices=["debug", "info", "warning", "error"],
            default="info",
        )

        args = parser.parse_args()
        run_command(args)


if __name__ == "__main__":
    main()
