name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  go:
    name: Go build, lint, test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Go fmt check
        run: |
          fmt_out=$(gofmt -l . || true)
          if [ -n "$fmt_out" ]; then
            echo "Run 'go fmt' on the following files:" >&2
            echo "$fmt_out" >&2
            exit 1
          fi

      - name: Go vet
        run: go vet ./...

      - name: Build all packages
        run: go build ./...

      - name: Build examples
        run: go build ./examples/basic

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      - name: Test
        run: go test ./...

  python:
    name: Python lint and tests (uv)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker/python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v4

      - name: Sync dependencies
        run: uv sync --all-extras --dev

      - name: Ruff check
        run: uv run ruff check .

      - name: Ruff format check
        run: uv run ruff format --check .

      - name: Pytest
        run: uv run pytest -q

  links:
    name: README and docs link check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --accept 200..299,403 --max-concurrency 4 --timeout 20s README.md docs/**/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

